### PR TITLE
Advanced counter: created a basic relay

### LINKED ISSUE #18: Advanced counter: latency relay app w/ postgres

### PR DESCRIPTION
**Pull request by icehaunter**
Closes #18

### CODE REVIEW

**Comment by thruflo** [comment]
Not necessarily this week but generally I imagine a relay app may be useful to cut out (and later generalise) as a minimal standalone app, rather than being part of / coupling to the specific demo app.

**Comment by thruflo** [comment]
This all looks good to me. I have two suggestions:

1. is it worth a pass through and cut out of necessary Phoenix boilerplate? Or do you want to keep it in their for future use? I's lean towards strip out, so the signal to noice ratio as example code is higher
2. guessing you plan to circle back to this in a future issue but fwiw, I'd be fleshing out the readme's a bit as you go, partly to just explain what's what whilst you're doing it -- here there's the root folder then the three apps, rather than having generic Phoenix docs, then it's nice to have something more specific

**Comment by icehaunter** [comment]
@thruflo I wanted to get this working, but I agree on the signal-to-noise ration. I intended to do a complete pass over the code with cleanup, readme & comments when we're settled that this fullfills our needs. If you'd rather I can do it in this PR instead

**Review by thruflo — APPROVED** [review]
All good to cleanup as a later pass :+1:

**Pull request merged**
